// Generated by the retired music_editor.html dev tool: themes edited in the
// browser were saved here and override the composed versions in
// buildMusicThemes(), for the game, the tests, and the render tool alike.
import type { Theme } from './music';

export const MUSIC_OVERRIDES: Record<string, Theme> = {
};
